export const NAVIGATION = {
  home: 'Home',
  login: 'Login',
  profile: 'Profile',
  followers : 'Followers',
  following : 'Following',
  profileSetting : 'ProfileSetting',
  userProfile : 'UserProfile',
  editProfile : "EditProfile",
  notificationSettings : "NotificationSettings",
  blockedUsers : "BlockedUsers",
  message: 'Message',
  exclusive: 'Exclusive',
  giveaway: 'Giveaway',
  homeNavigator: 'HomeNavigator',
  messageNavigator: 'MessageNavigator',
  exclusiveNavigator: 'ExclusiveNavigator',
  giveawayNavigator: 'GiveawayNavigator',
  profileNavigator: 'ProfileNavigator',
};
