export const NAVIGATION = {
  welcome: 'Welcome',
  home: 'Home',
  login: 'Login',
  enterOtp: 'EnterOtp',
  setupUserId: 'SetupUserId',
  profile: 'Profile',
  message: 'Message',
  exclusive: 'Exclusive',
  giveaway: 'Giveaway',
  homeNavigator: 'HomeNavigator',
  messageNavigator: 'MessageNavigator',
  exclusiveNavigator: 'ExclusiveNavigator',
  giveawayNavigator: 'GiveawayNavigator',
  profileNavigator: 'ProfileNavigator',
  signUp: 'SignUp',
  addProfilePicture: 'AddProfilePicture',
  adjustPicture: 'AdjustPicture',
};
