export const en = {
  common: {
    loading: 'Loading',
    connectionError: 'Connection error',
  },
  home: {
    header: 'Home',
    message: 'Welcome',
    variant: 'App variant: ',
    seeAllComments : 'See All Comments...',
    newFeed : 'News Feed',
    vipArea : 'VIP Area',
    recent : 'Recent',
    followingOnly : 'Following Only',
    sortByFeed : 'Sort By Feed',
    popularToday : 'Popular Today',
    popularThisWeek : 'Popular This Week',
    popularThisMonth : 'Popular this Month'
  },
  login: {
    username: 'Username',
    usernameHint: 'Enter your username',
    button: 'Login',
    password: 'Password',
    passwordHint: 'Enter your password',
    invalidCredentials: 'Invalid Username/Password',
    enterPhoneNumber: 'Enter your phone number',
    phoneNumber: 'Phone Number',
    continue: 'Continue',
    loginOrSignup: 'Login or Signup',
    byContinue: 'By continuing, you are agreeing to the ',
    termsAndConditions: 'Terms & Conditions',
    and: ' and ',
    privacyPolicy: 'Privacy Policy',
  },
  enterOtp: {
    title: 'Enter OTP to \ncontinue',
    enterTheVerificationCode:
      'Please enter the verification code that was sent to',
    edit: 'Edit',
    sorryCodeDidnotMatch: 'Sorry, the code didn’t match. Resend',
  },
  setupUserId: {
    title: 'Setup your \nUser ID',
    subtitle: 'Select your User ID',
    placeholder: '@username',
  },
  profile: {
    message: 'This screen has the iOS native large header.',
    header: 'Profile',
    logout: 'Logout',
    feedTitle: 'Share To Feed',
    feedLebel: "What's on your mind?",
    follow : 'Follow',
    unfollow : 'Unfollow',
    followers : 'Followers',
    following : 'Following',
    myFollowers: 'My Followers',
    myFollowing: 'My Following',
    myStatus: 'My Status',
    myActivity: 'My Activity',
    sendPrivateMessage : 'Send a private Message',
    report : 'Report',
    block : 'Block',
    unblock : 'Unblock',
    settings : 'Settings',
    vipMemberShip : 'VIP Membership',
    upgradeMembership : 'Upgrade to VIP Mebmership',
    upgradeLebel : 'Get the best out of JatieVIP',
    editProfile : 'Edit Profile',
    blockedUsers  : 'Blocked Users',
    notificationSettings : 'Notification Settings',
    appVersion : 'App Version 1.0.0',
    copyRightText : '©JatieVIP, Inc. All rights reserved',
    notificatin : 'Notification',
    notificatins : 'Notifications',
    fromMembers : 'From Members',
    reactTo : 'Someone reacts to my post',
    commentsOn : 'Someone comments on my post',
    ImFollowing : "Someone I'm following posts",
    fromJatie : 'From Jatie',
    jatiePost : 'Jatie posts',
    JatieLive : 'Jatie goes live',
    beforeLive : 'One hour before Jatie goes live',
    editProfile : 'Edit Profile',
    profilePic : 'Profile Picture',
    search : 'Search',
    upgradeTo : 'Upgrade To',
    vipMemberShip : 'VIP Membership',
    benefits : 'Benefits',
    benefit_1 : 'Access to all VIP Exclusive Content',
    benefit_2 : 'Access to exclusive VIP Giveaways',
    benefit_3 : 'Private message from Josh and Katie',
    benefit_4 : 'VIP Member only feed',
    benefit_5 : 'VIP only live streams and one-on-one' ,
    searchUser : 'Search Users',
    searchForUsers : 'Search for the users',
    searchResult : 'Recent Searches & Results',
    unreadOnly : 'Unread Only',
    youAreVIP : 'You are a VIP Member',
    adminTools : 'Admin Tools',
    manageReports : 'Manage Reports',
    userManagement : 'User Management',
    analytics : 'Analytics',
    bannedUsers : 'Banned Users',
    reported : 'Reported',
    reason : 'Reasion :',
    ban : 'Ban'

  },
  Welcome: {
    login: 'Login',
    signup: 'Sign Up',
    copyright: '© JatieVIP, Inc. All rights reserved.',
  },
  SignUp: {
    title: 'Tell us a little more about yourself',
    yourName: 'Your Name',
    name: 'Enter your name',
    email: 'Email',
    emailPlaceHolder: 'Enter your email',
    birthday: 'Birthday',
    gender: 'Gender',
    country: 'Country',
    dobPlaceHolder: 'Select your date of birth',
    genderPlaceHolder: 'Select your gender',
    countryPlaceHolder: 'Select your country',
  },
  addYourProfilePicture: {
    title: 'Add Your Profile \nPicture',
    upload: 'Upload',
    Finish: 'Finish',
    skip: 'Skip',
    remove: 'Remove',
    replace: 'Replace',
    uploadFromCamera: 'Upload from Camera',
    uploadFromGallery: 'Upload from Gallery',
    adjustPicture: 'Adjust Picture',
    cropAndClose: 'Crop & Close',
  },
};
