export const en = {
  common: {
    loading: 'Loading',
    connectionError: 'Connection error',
  },
  home: {
    header: 'Home',
    message: 'Welcome',
    variant: 'App variant: ',
  },
  login: {
    username: 'Username',
    usernameHint: 'Enter your username',
    button: 'Login',
    password: 'Password',
    passwordHint: 'Enter your password',
    invalidCredentials: 'Invalid Username/Password',
    enterPhoneNumber: 'Enter your phone number',
    phoneNumber: 'Phone Number',
    continue: 'Continue',
    loginOrSignup: 'Login or Signup',
    byContinue: 'By continuing, you are agreeing to the ',
    termsAndConditions: 'Terms & Conditions',
    and: ' and ',
    privacyPolicy: 'Privacy Policy',
  },
  enterOtp: {
    title: 'Enter OTP to \ncontinue',
    enterTheVerificationCode:
      'Please enter the verification code that was sent to',
    edit: 'Edit',
    sorryCodeDidnotMatch: 'Sorry, the code didn’t match. Resend',
  },
  setupUserId: {
    title: 'Setup your \nUser ID',
    subtitle: 'Select your User ID',
    placeholder: '@username',
  },
  profile: {
    header: 'Profile',
    logout: 'Logout',
    feedTitle: 'Share To Feed',
    feedLebel: "What's on your mind?",
    followers: 'Followers',
    following: 'Following',
    myStatus: 'My Status',
    myActivity: 'My Activity',
    message: 'This screen has the iOS native large header.',
  },
  Welcome: {
    login: 'Login',
    signup: 'Sign Up',
    copyright: '© JatieVIP, Inc. All rights reserved.',
  },
  SignUp: {
    title: 'Tell us a little more about yourself',
    yourName: 'Your Name',
    name: 'Enter your name',
    email: 'Email',
    emailPlaceHolder: 'Enter your email',
    birthday: 'Birthday',
    gender: 'Gender',
    country: 'Country',
    dobPlaceHolder: 'Select your date of birth',
    genderPlaceHolder: 'Select your gender',
    countryPlaceHolder: 'Select your country',
  },
  addYourProfilePicture: {
    title: 'Add Your Profile \nPicture',
    upload: 'Upload',
    Finish: 'Finish',
    skip: 'Skip',
    remove: 'Remove',
    replace: 'Replace',
    uploadFromCamera: 'Upload from Camera',
    uploadFromGallery: 'Upload from Gallery',
    adjustPicture: 'Adjust Picture',
    cropAndClose: 'Crop & Close',
  },
};
