export const en = {
  common: {
    loading: 'Loading',
    connectionError: 'Connection error',
  },
  userType: {
    free: 'Free',
    vip: 'VIP',
    admin: 'Admin',
  },
  home: {
    header: 'Home',
    message: 'Welcome',
    variant: 'App variant: ',
    comments: 'Comments',
    seeAllComments: 'See All Comments...',
    newFeed: 'News Feed',
    vipArea: 'VIP Area',
    recent: 'Recent',
    followingOnly: 'Following Only',
    sortByFeed: 'Sort By Feed',
    popularToday: 'Popular Today',
    popularThisWeek: 'Popular This Week',
    popularThisMonth: 'Popular this Month',
    typeComment: 'Type your comment here',
    replyTo: 'Reply to',
    shareToFeed: 'Share To Feed',
    whatOnYourMind: "What's on your mind?",
    shareToVipOnly: 'Share to VIP Only',
    post: 'post',
    next: 'Next',
    postOptions: 'Post Options',
    schedulePost: 'Schedule Post',
    seeSchedulePost: 'See Schedule posts',
    forVIPsOnly: 'For VIPs Only',
    pinThisPost: 'Pin this post',
    goingLive: 'Going Live',
    goingLiveLebel:
      'If you enable this, users will get notifications before the event',
    thisIsAnAd: 'This is an Ad',
    adLebel:
      'If selected, users will see this as an Ad. Reactions & comments will be disabled.',
    publishingDate: 'Publishing Date',
    ExpirationDate: 'Expiration Date',
    selectTimeAndDate: 'Select Date & Time',
    scheduledPost: 'Scheduled Posts',
    learMore: 'Learn More',
    sponsordPost: 'Sponsored Post',
    selectReason: 'Select Reason',
    reportMessage:
      'Thanks for reporting your concern. We will take down or ban this user if we find violation of our terms of services.',
  },
  sortBy: {
    recent: 'Recent',
    today: 'Today',
    week: 'Week',
    month: 'Month',
  },

  login: {
    username: 'Username',
    usernameHint: 'Enter your username',
    button: 'Login',
    password: 'Password',
    passwordHint: 'Enter your password',
    invalidCredentials: 'Invalid Username/Password',
    enterPhoneNumber: 'Enter your phone number',
    phoneNumber: 'Phone Number',
    continue: 'Continue',
    loginOrSignup: 'Login or Signup',
    byContinue: 'By continuing, you are agreeing to the ',
    termsAndConditions: 'Terms & Conditions',
    and: ' and ',
    privacyPolicy: 'Privacy Policy',
  },
  enterOtp: {
    title: 'Enter OTP to \ncontinue',
    enterTheVerificationCode:
      'Please enter the verification code that was sent to',
    edit: 'Edit',
    sorryCodeDidnotMatch: 'Sorry, the code didn’t match. Resend',
  },
  setupUserId: {
    title: 'Setup your \nUser ID',
    subtitle: 'Select your User ID',
    placeholder: '@username',
  },
  profile: {
    message: 'This screen has the iOS native large header.',
    header: 'Profile',
    logout: 'Logout',
    feedTitle: 'Share To Feed',
    feedLebel: "What's on your mind?",
    follow: 'Follow',
    unfollow: 'Unfollow',
    followers: 'Followers',
    following: 'Following',
    myFollowers: 'My Followers',
    myFollowing: 'My Following',
    myStatus: 'My Status',
    myActivity: 'My Activity',
    sendPrivateMessage: 'Send a private Message',
    report: 'Report',
    block: 'Block',
    unblock: 'Unblock',
    settings: 'Settings',
    vipMemberShip: 'VIP Membership',
    upgradeMembership: 'Upgrade to VIP Mebmership',
    upgradeLebel: 'Get the best out of JatieVIP',
    editProfile: 'Edit Profile',
    blockedUsers: 'Blocked Users',
    notificationSettings: 'Notification Settings',
    appVersion: 'App Version 1.0.0',
    copyRightText: '©JatieVIP, Inc. All rights reserved',
    notificatin: 'Notification',
    notificatins: 'Notifications',
    fromMembers: 'From Members',
    reactTo: 'Someone reacts to my post',
    commentsOn: 'Someone comments on my post',
    ImFollowing: "Someone I'm following posts",
    fromJatie: 'From Jatie',
    jatiePost: 'Jatie posts',
    JatieLive: 'Jatie goes live',
    beforeLive: 'One hour before Jatie goes live',
    editProfile: 'Edit Profile',
    profilePic: 'Profile Picture',
    search: 'Search',
    upgradeTo: 'Upgrade To',
    vipMemberShip: 'VIP Membership',
    cancelMemberShip: 'Cancel Membership',
    cancelVipMembership: 'Cancel VIP Membership',
    cencelMessage:
      'Are you sure want to cancel? You will lose the following benefits',
    benefits: 'Benefits',
    benefit_1: 'Access to all VIP Exclusive Content',
    benefit_2: 'Access to exclusive VIP Giveaways',
    benefit_3: 'Private message from Josh and Katie',
    benefit_4: 'VIP Member only feed',
    benefit_5: 'VIP only live streams and one-on-one',
    monthlyPlan: '$9.99/Month',
    yearlyPlan: '$99/Year',
    upgradeYearlySubsription: 'Upgrade to Yearly Subscription',
    saveByYearlyPlan: 'Save $20.88 by choosing the Yearly plan',
    searchUser: 'Search Users',
    searchForUsers: 'Search for the users',
    searchResult: 'Recent Searches & Results',
    unreadOnly: 'Unread Only',
    youAreVIP: 'You are a VIP Member',
    adminTools: 'Admin Tools',
    manageReports: 'Manage Reports',
    userManagement: 'User Management',
    analytics: 'Analytics',
    bannedUsers: 'Banned Users',
    reported: 'Reported',
    reason: 'Reasion : Explicit Content',
    ban: 'Ban',
    unban: 'Unban',
    upvoted: 'Upvoted',
    downVoted: 'Downvoted',
    commented: 'Commented',
    post: 'Post',
    message: 'Message',
    areYouSureWantToBan: 'Are you sure want to ban this user?',
    freeMember: 'Free Member',
    thisPost: 'this post',
    yesBan: 'Yes Ban',
    DoNotBan: "No, Don't Ban",
    renews: 'Renews on December 10,2023',
    cancelAnyway: 'Cancel Anyway',
    doNotCancel: "Don't Cancel",
    closeMyAccount: 'Close My Account',
    cancelSubscription: 'How do i cancel my subscription?',
    rule1: '1. Login to www.jativip.com',
    rule2: "2. Click 'Manage",
    rule3: "3. Click 'Cancel Renewal'",
    closeWarning:
      "You can't close your account while your subsription is still active.",
    manageSubscription: 'Manage your subscription',
    closeConfirm:
      "Are you sure want to close your Account? This action can't be undone.",
  },
  Welcome: {
    login: 'Login',
    signup: 'Sign Up',
    copyright: '© JatieVIP, Inc. All rights reserved.',
  },
  SignUp: {
    title: 'Tell us a little more about yourself',
    yourName: 'Your Name',
    name: 'Enter your name',
    email: 'Email',
    emailPlaceHolder: 'Enter your email',
    birthday: 'Birthday',
    gender: 'Gender',
    country: 'Country',
    dobPlaceHolder: 'Select your date of birth',
    genderPlaceHolder: 'Select your gender',
    countryPlaceHolder: 'Select your country',
    loginPhone: 'Login Phone',
    loginFormBottomTxt: 'You used this phone number to Login your account',
  },
  addYourProfilePicture: {
    title: 'Add Your Profile \nPicture',
    upload: 'Upload',
    Finish: 'Finish',
    skip: 'Skip',
    remove: 'Remove',
    replace: 'Replace',
    uploadFromCamera: 'Upload from Camera',
    uploadFromGallery: 'Upload from Gallery',
    adjustPicture: 'Adjust Picture',
    cropAndClose: 'Crop & Close',
  },
  exclusive: {
    header: 'Exclusive',
    recent: 'Recent',
    adminPostHeader: 'Post an Exclusive Content',
    title: 'Title',
    nextButton: 'Next',
    postButton: 'Post',
    exclusiveButton: '+ Exclusive',
    schedulePost: 'Schedule Post',
    forVIPsOnly: 'For VIPs Only',
    pinThisPost: 'Pin this Post',
    vipOnly: 'VIP Only',
    remove: 'Remove',
    edit: 'Edit',
    image: 'image',
    video: 'video',
  },
  giveaway: {
    header: 'Giveaway',
    active: 'Active',
    past: 'Past',
    EndsIn: 'Ends in',
    learnMore: 'Learn More',
    title: 'Summer 2023 Giveaway',
    vipOnly: 'VIP Only',

    //onPress learn more
    expires: 'Expires in',
    joinThisGiveaway: 'Join This Giveaway',
    withdrawFromThisGiveaway: 'Withdraw from this Giveaway',
    winners: 'Winners',
    byJoining: 'By joining you are agreeing to the ',
    termsAndConsition: 'Giveaway Terms & Conitions',
    onlyUS:
      "Unfortunately, you can't join this giveaway. The prize ships only to US addresses",
    winner: 'Winner',
    winners: 'Winners',
    twentyThree: '23',

    //Admin
    newGiveaway: '+ New Giveaway',
    seeAllParticipants: 'See All Participants',
    editGiveaway: 'Edit Giveaway',
    endNow: 'End Now',
    removeThisGiveaway: 'Remove this Giveaway',
    participants: 'Participants',
    deletePost: 'Delete Post',
    ban: 'Ban',
    createGiveaway: 'Create A Giveaway',
    next: 'Next',
    minus: '-',

    //Admin Giveaway options
    giveawayOption: 'Giveaway Options',
    startDate: 'Start Date',
    endDate: 'End Date',
    numberOfWinners: 'Number of Winners',
    forVIPsOnly: 'For VIPs Only',
    usOnly: 'US-only',
    post: 'Post',

    //Alert

    follow: 'follow',
    message: 'message',
    report: 'report',
    blocked: 'blocked',
  },
  message: {
    message: 'Message',
    newMessage: '+ New Message',
    unreadOnly: 'Unread Only',
    archive: 'Archive',
    snoozeNotification: 'Snooze Notification',
    emptyTxt : "It's very quit here. Let's start a chat!"
  },
  operations: {
    save: 'Save',
    follow: 'Follow',
    unFollow: 'Unfollow',
    sendPrivateMessage: 'Send a Private Message',
    report: 'Report',
    remove: 'Remove',
    edit: 'Edit',
    ban: 'Ban',
    unBan: 'Unban',
    block: 'Block',
    unBlock: 'Unblock',
    imageFromCamera: 'Pickup From Camara',
    imageFromGallery: 'Select From Gallery',
    yes: 'Yes',
    no: 'No',
    ok: 'Ok',
    addComments: 'Add Comments',
    submit: 'Submit',
  },
};
